name: "gata_transformation"
version: "1.0.0"
config-version: 2

require-dbt-version: ">=1.8.0"

profile: "swamp-duck"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ init_artifact_tables() }}"

on-run-end:
  - "{{ upload_run_results() }}"
  - "{{ upload_model_definitions() }}"
  - "{{ upload_test_definitions() }}"
